### ISSUE TITLE
CI lacks environmental configuration sometimes.

### ISSUE THREAD

**Issue by Roiocam** [apache/pekko-persistence-jdbc#167]
```
./scripts/launch-postgres.sh: line 34: docker-compose: command not found
./scripts/launch-postgres.sh: line 35: docker-compose: command not found
./scripts/launch-postgres.sh: line 36: docker-compose: command not found
Postgres not available, retrying...
Postgres not available, retrying...
Postgres not available, retrying...
Postgres not available, retrying...
Postgres not available, retrying...
Postgres not available, retrying...
```

See:

- https://github.com/apache/pekko-persistence-jdbc/actions/runs/8534815285/job/23379933184?pr=158
- https://github.com/apache/pekko-persistence-jdbc/actions/runs/8534522155/attempts/1

**Comment by samueleresca** [comment]
Likely related to: https://github.com/orgs/community/discussions/116610
We probably need to move our CI to docker compose V2: https://docs.docker.com/compose/migrate/

**Comment by Roiocam** [comment]
> Likely related to: https://github.com/orgs/community/discussions/116610 We probably need to move our CI to docker compose V2: https://docs.docker.com/compose/migrate/

Thank you for providing the information! Looks like it works in #168
