### ISSUE TITLE
Migrator Integration tests are failing for multiple db servers

### ISSUE THREAD

**Issue by pjfanning** [apache/pekko-persistence-jdbc#198]
see https://github.com/apache/pekko-persistence-jdbc/actions/runs/9247671484/job/25475898553, https://github.com/apache/pekko-persistence-jdbc/actions/runs/9247671480/job/25445435838, https://github.com/apache/pekko-persistence-jdbc/actions/runs/9247671477/job/25445328062

(MySQL, Oracle, SQL Server)

@Roiocam is this a release blocker or can we just disable the broken tests?

**Comment by Roiocam** [comment]
These failures were caused by #180 and fixed in #195.
