### ISSUE TITLE
Implement `deleteObject(persistenceId: String, revision: Long)` properly

### ISSUE THREAD

**Issue by mdedetrich** [apache/pekko-persistence-jdbc#30]
As can be seen from https://github.com/apache/incubator-pekko-persistence-jdbc/blob/db5733e60fffb99d3d822d3d60199ec2f0890278/core/src/main/scala/org/apache/pekko/persistence/jdbc/state/scaladsl/JdbcDurableStateStore.scala#L117-L118 the current implementation of `deleteObject(persistenceId: String, revision: Long)` just defers to `deleteObject(persistenceId: String)` (which means it ignores the revision).

The implementation should instead be improved so it only deletes correct revision.

**Comment by pjfanning** [comment]
#156 merged
