### ISSUE TITLE
Make DurableState possible to use with other databases

### ISSUE THREAD

**Issue by zackman0010** [apache/pekko-persistence-jdbc#56]
I know the first priority is getting the 1.0.0 version out, so this won't be handled for a while, but I figured I'd go ahead and submit this issue so it might could be looked at in the future.

One of the things currently unimplemented even in the original akka-persistence-jdbc is Durable State for any database other than Postgres or H2. This limitation is not even mentioned in the documentation, it just throws errors at runtime if you try to use a different database (Oracle in our case) for Durable State. I'd love to see it finally get fully implemented in Pekko.

**Comment by pjfanning** [comment]
thanks @zackman0010 - any interest in trying to do a PR yourself?

Would you also help us out by suggesting a doc change that could be made to note this? Somewhere in https://pekko.apache.org/docs/pekko-persistence-jdbc/current/

**Comment by pjfanning** [comment]
thanks @zackman0010 - if javadoc/scaladoc is the right place to note this, then we can do that. I've never used this module so I'd prefer to get advice from a user about this.

**Comment by zackman0010** [comment]
@pjfanning Thanks for merging the docs! Can you reopen this issue? Looks like my comment on the PR made it think it was supposed to close this, lol.
